#! /bin/sh

# Make sure to load shared things (e.g. 50-systemd-user.sh that imports DISPLAY
# and XAUTHORITY environment variables
if [ -d /etc/X11/xinit/xinitrc.d ] ; then
 for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
  [ -x "$f" ] && . "$f"
 done
 unset f
fi

# Usual defaults and keymaps config
userresources=$HOME/.Xresources
usermodmap=$HOME/.Xmodmap
sysresources=/etc/X11/xinit/.Xresources
sysmodmap=/etc/X11/xinit/.Xmodmap

# Merge these defaults in
for xfile in $sysresources $sysmodmap $userresource $usermodmap; do
  if [ -f $xfile ]; then
      xrdb -merge $xfile
  fi
done

# TODO: stop hardcoding that
export TERMINAL=alacritty
# TODO: template that
exec i3
