#! /bin/sh

# TODO: template that
if [ -d /etc/X11/xinit/xinitrc.d ] ; then
 for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
  [ -x "$f" ] && . "$f"
 done
 unset f
fi
exec i3


# Usual defaults and keymaps config
userresources=$HOME/.Xresources
usermodmap=$HOME/.Xmodmap
sysresources=/etc/X11/xinit/.Xresources
sysmodmap=/etc/X11/xinit/.Xmodmap

# Merge these defaults in
for xfile in $sysresources $sysmodmap $userresource $usermodmap; do
  if [ -f $xfile ]; then
      xrdb -merge $xfile
  fi
done
